[pytest]
testpaths = tests
pythonpath = .
addopts =
    -ra
    --strict-markers
    --alluredir=allure-results
    --clean-alluredir
    --screenshot=only-on-failure
    --video=retain-on-failure
    --tracing=retain-on-failure
